import img1 from "../../public/img-1.png";
import img2 from "/img-2.png";

// Main object with whole prooducts data
const productsObject = [
  {
    id: 0,
    image: img1,
    title: "WW90T754ABT, Pralka QuickDrive™, 9 kg, biała",
    capacity: 9,
    size: "55 x 60 x 85 cm",
    productFunc: [
      "Drzwi AddWash™",
      "Panel AI Control",
      "Silnik inwerterowy",
      "Wyświetlacz elektroniczny",
    ],
    electricalClass: "a",
    price: 3199,
    popularity: 1,
    isChoosen: false,
  },
  {
    id: 1,
    image: img2,
    title: "WW10T654DLH, Pralka EcoBubble™, 10,5 kg, biała",
    capacity: 10.5,
    size: "55 x 60 x 85 cm",
    productFunc: [
      "Drzwi AddWash™",
      "Panel AI Control",
      "Silnik inwerterowy",
      "Wyświetlacz elektroniczny",
    ],
    electricalClass: "b",
    price: 3199,
    popularity: 2,
    isChoosen: false,
  },
  {
    id: 2,
    image: img2,
    title: "WW90T654DLH, Pralka EcoBubble™, 9 kg, biała",
    capacity: 8,
    size: "55 x 60 x 85 cm",
    productFunc: [
      "Drzwi AddWash™",
      "Panel AI Control",
      "Silnik inwerterowy",
      "Wyświetlacz elektroniczny",
    ],
    electricalClass: "c",
    price: 3199,
    popularity: 3,
    isChoosen: false,
  },
  {
    id: 3,
    image: img1,
    title: "WW90T754ABT, Pralka QuickDrive™, 9 kg, biała",
    capacity: 9,
    size: "55 x 60 x 85 cm",
    productFunc: [
      "Drzwi AddWash™",
      "Panel AI Control",
      "Silnik inwerterowy",
      "Wyświetlacz elektroniczny",
    ],
    electricalClass: "d",
    price: 3199,
    popularity: 4,
    isChoosen: false,
  },
  {
    id: 4,
    image: img2,
    title: "WW10T654DLH, Pralka EcoBubble™, 10,5 kg, biała",
    capacity: 10.5,
    size: "55 x 60 x 85 cm",
    productFunc: [
      "Drzwi AddWash™",
      "Panel AI Control",
      "Silnik inwerterowy",
      "Wyświetlacz elektroniczny",
    ],
    electricalClass: "e",
    price: 3199,
    popularity: 5,
    isChoosen: false,
  },
  {
    id: 5,
    image: img2,
    title: "WW90T654DLH, Pralka EcoBubble™, 8 kg, biała",
    capacity: 8,
    size: "55 x 60 x 85 cm",
    productFunc: [
      "Drzwi AddWash™",
      "Panel AI Control",
      "Silnik inwerterowy",
      "Wyświetlacz elektroniczny",
    ],
    electricalClass: "f",
    price: 3199,
    popularity: 6,
    isChoosen: false,
  },
];

export default productsObject;
